### PR TITLE
Implement for a subset of tuples and arrays

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by HeroicKatora** [comment]
This is unsound. The layout of tuples is not defined.

**Comment by HeroicKatora** [comment]
Reference: https://github.com/rust-lang/unsafe-code-guidelines/issues/36

**Comment by kornelski** [comment]
Ugh, that sucks. There's no sensible way to implement homogeneous tuple other than as contiguous array, so Rust is leaving this undefined for no good reason :(

**Comment by HeroicKatora** [comment]
@kornelski The arrays are fine, `bytemuck` has them as well. Only the tuples can't be added.

**Pull request closed without merging**
